language: node_js
node_js:
  - "node"
  - "8"
  - "7"

script:
  - npm test

stages:
  - name: npm release
    if: branch = master AND type = push AND tag = true

jobs:
  include:
    - stage: npm release
      node_js: "node"
      script:
        - npm run build
        - touch ~/.npmrc
        - echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_AUTH_TOKEN" >> ~/.npmrc
        - npm publish
