language: node_js
node_js:
  - "node"
  - "8"
  - "7"

script:
  - npm test

jobs:
  include:
    - stage: npm release
      node_js: "node"
      if: branch = master AND tag = true
      script:
        - npm run build
        - touch ~/.npmrc
        - echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_AUTH_TOKEN" >> ~/.npmrc
        - npm publish
