language: node_js
node_js:
  - "10"
  - "8"
  - "7"

stages:
  - test
  - name: npm release
    if: branch = master AND tag = true AND type = push

jobs:
  include:
    - stage: test
      script: npm test
    - stage: npm release
      node_js: "node"
      script:
        - npm run build
        - touch ~/.npmrc
        - echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_AUTH_TOKEN" >> ~/.npmrc
        - npm publish
