language: node_js
node_js:
  - "node"
  - "7"

cache:
  directories:
    - "node_modules"

script:
  - npm test
  - npm run build

deploy:
  provider: npm
  email: $NPM_PUBLISH_EMAIL
  api_key: $NPM_PUBLISH_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: master