language: node_js

stages:
  - test
  - name: npm release
    if: branch = master AND tag = true AND type = push

jobs:
  include:
    - stage: test
      node_js:
        - "node"
        - "8"
        - "7"
      script: npm test
    - stage: npm release
      node_js: "node"
      script:
        - npm run build
        - touch ~/.npmrc
        - echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_AUTH_TOKEN" >> ~/.npmrc
        - npm publish
